"""
Robustness/accuracy report across all test lease documents.

Runs extraction against every sample PDF (the original 2 fixtures plus
the 3 synthetic documents generated by create_synthetic_leases.py, each
with meaningfully different structure, phrasing, formatting, and
formality) and prints a field-by-field accuracy summary. A field is
"correct" if it was expected to be found and the extracted value
contains the expected substring, or if it was expected to be Not Found
and the extractor correctly returned null.

This is a reporting/diagnostic script (not a pass/fail gate) — its job
is to surface which fields are weak across multiple documents so they
can be prioritized for further regex work.
"""

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.pdf_extractor import PDFExtractor
from app.field_extractor import FieldExtractor
from create_synthetic_leases import (
    create_retail_lease,
    create_office_lease,
    create_casual_sublease,
)


ALL_FIELDS = [
    "tenant", "landlord", "rent_amount", "lease_start_date", "lease_end_date",
    "property_address", "security_deposit", "cam_charges", "rent_escalation",
    "renewal_options", "permitted_use", "exclusivity_clause",
    "insurance_requirements", "default_cure_period",
]


def run_report():
    docs = [
        {
            "name": "residential.pdf",
            "path": "sample_lease.pdf",
            "expected": {
                "tenant": "John Smith",
                "landlord": "Property Management LLC",
                "rent_amount": "$2,500",
                "lease_start_date": "January 15, 2024",
                "lease_end_date": "January 14, 2025",
                "property_address": "123 Main Street",
                "security_deposit": "$2,500",
                "cam_charges": None,
                "rent_escalation": None,
                "renewal_options": None,
                "permitted_use": None,
                "exclusivity_clause": None,
                "insurance_requirements": None,
                "default_cure_period": None,
            },
        },
        {
            "name": "commercial.pdf",
            "path": "sample_lease_commercial.pdf",
            "expected": {
                "tenant": "Blue Sky Coffee Roasters",
                "landlord": "Meridian Properties Group",
                "rent_amount": "$6,250.00",
                "lease_start_date": "April 1, 2025",
                "lease_end_date": "March 31, 2030",
                "property_address": "4200 Commerce Parkway",
                "security_deposit": "$12,500.00",
                "cam_charges": "$875.00",
                "rent_escalation": "3%",
                "renewal_options": "2 option",
                "permitted_use": "coffee shop",
                "exclusivity_clause": "coffee",
                "insurance_requirements": "$2,000,000",
                "default_cure_period": "10 days",
            },
        },
        {"name": "retail_lease.pdf", "path": "retail_lease.pdf", "expected": create_retail_lease()},
        {"name": "office_lease.pdf", "path": "office_lease.pdf", "expected": create_office_lease()},
        {"name": "casual_sublease.pdf", "path": "casual_sublease.pdf", "expected": create_casual_sublease()},
    ]

    pdf_extractor = PDFExtractor()
    field_extractor = FieldExtractor()

    # field_name -> [num_correct, num_total]
    tally = {f: [0, 0] for f in ALL_FIELDS}
    rows = []

    for doc in docs:
        path = os.path.join(os.path.dirname(__file__), doc["path"])
        with open(path, 'rb') as f:
            pages = pdf_extractor.extract_text(f, pdf_path=path)

        extracted = field_extractor.extract_fields(pages)

        for field in ALL_FIELDS:
            expected_value = doc["expected"].get(field)
            actual_value = extracted[field]["value"]
            confidence = extracted[field]["confidence"]

            if expected_value is None:
                correct = actual_value is None
            else:
                correct = bool(actual_value) and expected_value.lower() in str(actual_value).lower()

            tally[field][1] += 1
            if correct:
                tally[field][0] += 1

            rows.append({
                "doc": doc["name"],
                "field": field,
                "expected": expected_value,
                "actual": actual_value,
                "confidence": confidence,
                "correct": correct,
            })

    # Per-document detail
    for doc in docs:
        print("=" * 70)
        print(f"DOCUMENT: {doc['name']}")
        print("=" * 70)
        for row in rows:
            if row["doc"] != doc["name"]:
                continue
            mark = "✓" if row["correct"] else "✗"
            conf = row["confidence"] or "-"
            print(f"{mark} {row['field']:24s} conf={conf:8s} expected={str(row['expected'])!r:40s} actual={row['actual']!r}")
        print()

    # Field-by-field accuracy summary
    print("=" * 70)
    print("FIELD-BY-FIELD ACCURACY SUMMARY (across all 5 documents)")
    print("=" * 70)
    weak_fields = []
    for field in ALL_FIELDS:
        correct, total = tally[field]
        pct = 100 * correct / total
        flag = ""
        if pct < 80:
            flag = "  <-- WEAK"
            weak_fields.append(field)
        print(f"{field:24s} {correct}/{total}  ({pct:5.1f}%){flag}")

    total_correct = sum(t[0] for t in tally.values())
    total_fields = sum(t[1] for t in tally.values())
    print("-" * 70)
    print(f"{'OVERALL':24s} {total_correct}/{total_fields}  ({100*total_correct/total_fields:5.1f}%)")
    print()

    if weak_fields:
        print(f"Fields below 80% accuracy: {', '.join(weak_fields)}")
    else:
        print("No fields below 80% accuracy threshold.")

    return weak_fields


if __name__ == "__main__":
    run_report()
